# Generated by Django 4.1.4 on 2022-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='PatientIC',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='UserDOB',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
