# Generated by Django 4.1.4 on 2022-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0003_patients_patientic_users_userdob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcedureStatus', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('Remarks', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='UserName',
            new_name='UserFirstName',
        ),
        migrations.AddField(
            model_name='patients',
            name='PatientDateOFAppt',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='PatientProcedure',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='PatientTimeofAppt',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='UserLastName',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='UserSpecialty',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
