# Generated by Django 4.1.4 on 2022-12-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0004_forms_rename_username_users_userfirstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='PatientDateOFAppt',
            new_name='PatientDateOfAppt',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='PatientTimeofAppt',
            new_name='PatientTimeOfAppt',
        ),
    ]
