# Generated by Django 4.1.4 on 2022-12-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0005_rename_patientdateofappt_patients_patientdateofappt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='nameofPatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklistapp.patients'),
        ),
    ]
