# Generated by Django 4.1.4 on 2022-12-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0007_forms_asthma_forms_betablockers_forms_consentform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='nameofPatient',
            new_name='PatientName',
        ),
    ]
