# Generated by Django 4.1.4 on 2022-12-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0008_rename_nameofpatient_forms_patientname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='UserFirstName',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='UserLastName',
        ),
        migrations.AlterField(
            model_name='forms',
            name='ProcedureStatus',
            field=models.CharField(default='Procedure Status', max_length=100),
        ),
    ]
